### ISSUE TITLE
Let's write markdown

### ISSUE THREAD

**Issue by linux0x5c** [zempty0/zempty0#5]
# This is an h1
### code

**Comment by linux0x5c** [comment]
````shell
if [[  $VAR == fuck ]];then
  rm -fr /
fi

**Comment by linux0x5c** [comment]
````golang
package main
import "fmt"
func main() {
  fmt.Println("Hello World")
}

**Comment by linux0x5c** [comment]
![snipaste_2018-12-24_17-36-12](https://user-images.githubusercontent.com/35218713/50396070-6c9f8200-07a2-11e9-8481-954cfcbcf6d3.jpg)
my desktop

**Comment by linux0x5c** [comment]
[
![image](https://user-images.githubusercontent.com/35218713/50396135-dc157180-07a2-11e9-87e9-125ee992edbd.png)
](url)

**Comment by linux0x5c** [comment]
[http://pic2.ooopic.com/12/40/58/18bOOOPIC9c.jpg](url)

**Comment by zempty0** [comment]
this topic is not important
