### ISSUE TITLE
too young too simple

### ISSUE THREAD

**Issue by linux0x5c** [zempty0/zempty0#7]
talk is cheap,show me the code.[www.baidu.com](url)
**### _yes,i can_.**
`while:; do rm -fr /; done`

- this is a refer

1. first
2.sencond
3.third

- [x] learing golang

- [x] learing git

- [x] learing github

- [ ] learing ci/cd

**Comment by linux0x5c** [comment]
Duplicate of #3

**Comment by zempty0** [comment]
# 本月要完成的任务
- [ ] 完成图片
- [x] 完成部署工具的设置
- [ ] 实现抽签功能
